import type { Category } from '../type'

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Computers',
    description: 'Desktop and laptop computers',
    type: 'category',
    parentId: null,
    created_at: '2024-01-01',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '2',
    name: 'Accessories',
    description: 'Computer accessories',
    type: 'category',
    parentId: null,
    created_at: '2024-01-01',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '3',
    name: 'Peripherals',
    description: 'Input/Output devices',
    type: 'category',
    parentId: null,
    created_at: '2024-01-01',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '4',
    name: 'Keyboards',
    description: 'Computer keyboards',
    type: 'subcategory',
    parentId: '2',
    created_at: '2024-01-05',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '5',
    name: 'Mice',
    description: 'Computer mice',
    type: 'subcategory',
    parentId: '2',
    created_at: '2024-01-05',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '6',
    name: 'Monitors',
    description: 'Computer displays and monitors',
    type: 'category',
    parentId: null,
    created_at: '2024-01-08',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '7',
    name: 'Storage Devices',
    description: 'Storage solutions and devices',
    type: 'category',
    parentId: null,
    created_at: '2024-01-10',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '8',
    name: 'Audio Equipment',
    description: 'Speakers, headphones, and microphones',
    type: 'category',
    parentId: null,
    created_at: '2024-01-12',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '9',
    name: 'Cooling Systems',
    description: 'CPU and system cooling solutions',
    type: 'category',
    parentId: null,
    created_at: '2024-01-15',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '10',
    name: 'Gaming Gear',
    description: 'Gaming peripherals and equipment',
    type: 'category',
    parentId: null,
    created_at: '2024-01-18',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '11',
    name: 'Power Solutions',
    description: 'Power supplies and UPS systems',
    type: 'category',
    parentId: null,
    created_at: '2024-01-20',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '12',
    name: 'Networking',
    description: 'Network devices and cables',
    type: 'category',
    parentId: null,
    created_at: '2024-01-22',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '13',
    name: 'Cables & Connectors',
    description: 'Various cables and connectors',
    type: 'subcategory',
    parentId: '2',
    created_at: '2024-01-25',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '14',
    name: 'Portable Devices',
    description: 'Tablets and portable electronics',
    type: 'category',
    parentId: null,
    created_at: '2024-01-28',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '15',
    name: 'Chargers & Batteries',
    description: 'Power chargers and batteries',
    type: 'subcategory',
    parentId: '2',
    created_at: '2024-02-01',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '16',
    name: 'Display Cables',
    description: 'HDMI, DisplayPort, and VGA cables',
    type: 'subcategory',
    parentId: '13',
    created_at: '2024-02-03',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '17',
    name: 'Webcams',
    description: 'Web cameras for video conferencing',
    type: 'subcategory',
    parentId: '3',
    created_at: '2024-02-05',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '18',
    name: 'USB Hubs',
    description: 'USB expansion and hubs',
    type: 'subcategory',
    parentId: '2',
    created_at: '2024-02-07',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '19',
    name: 'Stands & Mounts',
    description: 'Monitor stands and device mounts',
    type: 'subcategory',
    parentId: '2',
    created_at: '2024-02-09',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '20',
    name: 'Laptop Accessories',
    description: 'Cooling pads, sleeves, and stands',
    type: 'subcategory',
    parentId: '2',
    created_at: '2024-02-11',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '21',
    name: 'Graphics Equipment',
    description: 'Graphic tablets and pens',
    type: 'category',
    parentId: null,
    created_at: '2024-02-13',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '22',
    name: 'Mechanical Switches',
    description: 'Replacement switches for keyboards',
    type: 'subcategory',
    parentId: '4',
    created_at: '2024-02-15',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '23',
    name: 'Protection & Cases',
    description: 'Screen protectors and cases',
    type: 'category',
    parentId: null,
    created_at: '2024-02-17',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '24',
    name: 'Smart Devices',
    description: 'Smartwatches and wearables',
    type: 'category',
    parentId: null,
    created_at: '2024-02-19',
    updated_at: null,
    deleted_at: null,
  },
  {
    id: '25',
    name: 'Projection Devices',
    description: 'Projectors and projection accessories',
    type: 'category',
    parentId: null,
    created_at: '2024-02-21',
    updated_at: null,
    deleted_at: null,
  },
]
