/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/categories/[id]/': RouteRecordInfo<'/categories/[id]/', '/categories/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/categories/create/': RouteRecordInfo<'/categories/create/', '/categories/create', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/products/[id]/': RouteRecordInfo<'/products/[id]/', '/products/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/products/': RouteRecordInfo<'/products/', '/products', Record<never, never>, Record<never, never>>,
    '/products/create/': RouteRecordInfo<'/products/create/', '/products/create', Record<never, never>, Record<never, never>>,
    '/users/[id]/': RouteRecordInfo<'/users/[id]/', '/users/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/create/': RouteRecordInfo<'/users/create/', '/users/create', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(protected)/categories/[id]/index.vue': {
      routes: '/categories/[id]/'
      views: never
    }
    'src/pages/(protected)/categories/index.vue': {
      routes: '/categories/'
      views: never
    }
    'src/pages/(protected)/categories/create/index.vue': {
      routes: '/categories/create/'
      views: never
    }
    'src/pages/(protected)/dashboard/index.vue': {
      routes: '/dashboard/'
      views: never
    }
    'src/pages/(public)/login/index.vue': {
      routes: '/login/'
      views: never
    }
    'src/pages/(protected)/products/[id]/index.vue': {
      routes: '/products/[id]/'
      views: never
    }
    'src/pages/(protected)/products/index.vue': {
      routes: '/products/'
      views: never
    }
    'src/pages/(protected)/products/create/index.vue': {
      routes: '/products/create/'
      views: never
    }
    'src/pages/(protected)/users/[id]/index.vue': {
      routes: '/users/[id]/'
      views: never
    }
    'src/pages/(protected)/users/index.vue': {
      routes: '/users/'
      views: never
    }
    'src/pages/(protected)/users/create/index.vue': {
      routes: '/users/create/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
